var n1 = 10;
var n2 = 5;
var result = n1 + n2;
console.log(`Addition (+) is: ${result} `);
console.log("----------------------------");
var n1 = 10;
var n2 = 5;
var result = n1 - n2;
console.log(`substraction (-) is: ${result}`);
console.log("-------------------------------");
var n1 = 10;
var n2 = 5;
var result = n1 * n2;
console.log(`mltiplication (*) is : ${result}`);
console.log("-------------------------------");
var n1 = 10;
var n2 = 5;
var result = n1 / n2;
console.log(`division (/) is : ${result}`);
console.log("-------------------------------");
var n1 = 10;
var n2 = 5;
var result = n1 % n2;
console.log(`modulus (%) is : ${result}`);
console.log("-------------------------------");
var n1 = 10;
var n2 = 5;
var result = n1 ** n2;
console.log(`exponentiation (**) is : ${result}`);
console.log("-------------------------------");
var n1 = 10;
var n2 = 5;
var result = n1 + + n2 ;
console.log(`increment (++) is : ${result}`);
console.log("-------------------------------");
var n1 = 10;
var n2 = 5;
var result = n1- -n2 ;
console.log(`decrement (--) is : ${result}`);
console.log("-------------------------------");